# Generated by Django 5.0.7 on 2025-04-17 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrectionConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable the auto-correction feature')),
                ('cutoff_time', models.TimeField(default=datetime.time(6, 0), help_text='Time threshold to determine if the current day should be considered or shifted to the previous day')),
            ],
            options={
                'db_table': 'attendance_correction_config',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tolerance_before_start_time', models.DurationField(blank=True, null=True)),
                ('tolerance_after_start_time', models.DurationField(blank=True, null=True)),
                ('tolerance_before_end_time', models.DurationField(blank=True, null=True)),
                ('tolerance_after_end_time', models.DurationField(blank=True, null=True)),
                ('grace_period_at_start_time', models.DurationField(blank=True, null=True)),
                ('grace_period_at_end_time', models.DurationField(blank=True, null=True)),
                ('absent_threshold', models.DurationField(blank=True, null=True)),
                ('half_day_threshold', models.DurationField(blank=True, null=True)),
                ('full_day_threshold', models.DurationField(blank=True, null=True)),
                ('overtime_threshold_before_start', models.DurationField(blank=True, null=True)),
                ('overtime_threshold_after_end', models.DurationField(blank=True, null=True)),
                ('lunch_in', models.TimeField(blank=True, null=True)),
                ('lunch_out', models.TimeField(blank=True, null=True)),
                ('lunch_duration', models.DurationField(blank=True, null=True)),
                ('night_shift', models.BooleanField(default=False)),
                ('include_lunch_break_in_half_day', models.BooleanField(default=False)),
                ('include_lunch_break_in_full_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='Shopfloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shopfloor',
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subdivision',
            },
        ),
    ]
