# Generated by Django 5.0.7 on 2025-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeid', models.CharField(blank=True, max_length=50, null=True)),
                ('log_datetime', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('serialno', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'all_logs',
                'indexes': [models.Index(fields=['employeeid', 'log_datetime'], name='all_emp_logdt'), models.Index(fields=['log_datetime'], name='all_logdt'), models.Index(fields=['direction'], name='all_dir')],
                'unique_together': {('employeeid', 'log_datetime', 'direction', 'source')},
            },
        ),
    ]
