# Generated by Django 5.0.7 on 2025-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alllogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='consider_first_weekly_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='consider_second_weekly_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_shift',
            field=models.BooleanField(default=False),
        ),
    ]
