# Generated by Django 5.0.7 on 2025-05-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_employee_consider_first_weekly_off_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fixed_shift',
            new_name='consider_fixed_shift',
        ),
    ]
